name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Commit new build
        run: |
          git config --local user.name "Github BUILD"
          git config --local user.email github-actions@github.com
          git add dist/index.js
          git commit -m "update index.js"
      - name: Push new index.js to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MASTER_ACCESS_TOKEN }}
          branch: 'master'
      - name: Test
        run: npm run test
      - name: Format
        run: npm run fmtcheck
      - name: "check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
          || (echo "##[error] found changed files after build. please 'npm run build && npm run fmt'" \
                   "and check in all changes" \
              && exit 1)
