name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete "index.js"
        run: |
          git config --local user.name "Github BUILD"
          git config --local user.email github-actions@github.com
          rm dist/*
          git rm dist/*
          git commit -m "remove index.js"
      - name: Install
        run: | 
          npm ci
          npm audit fix
      - name: Build
        run: npm run build
      - name: Commit new build
        run: |
          git add dist/index.js
          git add package-lock.json
          git commit -m "update index.js"
      - name: Push new index.js to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'
      - name: Test
        run: npm run test
      - name: Format
        run: npm run fmtcheck
